spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: user
    password: password
  h2:
    console:
      enabled: true


  security:
    oauth2:
      client:
        registration:
          todoist:
            redirect-uri: https://localhost:8080/api/v1/auth/callback