spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          todoist:
            redirect-uri: https://kitchen-assistant-app.onrender.com/api/v1/auth/callback