---
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  output:
    ansi:
      enabled: always

  sql:
    init:
      mode: always
  profiles:
    default: dev

logging:
  level:
    root: INFO

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

# получение token для запросов к YandexGPT:
JWT_TOKEN: "{\"yandexPassportOauthToken\":\"y0_AgAAAAB4pbvzAATuwQAAAAERiQoLAAAJDwu7zrdIMoZCxO3EGvZ8HE3S_A\"}"
gpt-token-url: "https://iam.api.cloud.yandex.net/iam/v1/tokens"

# данные для YandexGPT:
FOLDER_ID: "b1g9e9k3q9k3fptu8ka4"
gpt-api-url: "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"


